[package]
name = 'surge-config-server'
version = '0.1.0'
authors = ['Nearsyh <nearsy.h@gmail.com>']
edition = '2018'

[dependencies]
actix-web = '2'
actix-rt = '1'
actix = '0.9'
reqwest = '0.10'

[dependencies.tokio]
version = '0.2'
features = ['macros']
